import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FiSend, FiCpu, FiUser, FiSidebar, FiFileText, FiBarChart2, FiGlobe, FiPlus, FiMessageSquare, FiX, FiPaperclip, FiImage, FiMic } from 'react-icons/fi';

const mockHistory = [
  { id: 1, title: 'Global Broadcast Setup', date: 'Today' },
  { id: 2, title: 'User Suspension Query', date: 'Yesterday' },
  { id: 3, title: 'Revenue Report Gen', date: 'Oct 14' },
  { id: 4, title: 'Platform Health Check', date: 'Oct 12' },
];

const mockChat = [
  { id: 1, sender: 'user', text: "Give me a quick platform status report for today." },
  { id: 2, sender: 'ai', text: "Currently, there are **14,205** students and **845** teachers active on the platform. System health is at **99.9%**. I noticed one minor API warning from the billing integration, but it has resolved itself." },
  { id: 3, sender: 'user', text: "Who are the top 3 most active teachers this week?" },
  { id: 4, sender: 'ai', text: "Here are the top 3 most active educators by session duration:\n1. **Alice Johnson** (Westside High) - 45 active hours\n2. **Robert Smith** (Northwood Academy) - 42 active hours\n3. **Emily Chen** (East Valley High) - 38 active hours" },
  { id: 5, sender: 'user', text: "I need to look into Bilal Khan's account. Pull up his details." },
  { id: 6, sender: 'ai', text: "**Bilal Khan** (bilal.k@school.edu) is currently marked as `Suspended`. He is enrolled at Northwood Academy. \n\n**Reason for suspension:** Unpaid institution invoices. \n\nWould you like me to send an automated reminder to Northwood Academy's billing department?" },
  { id: 7, sender: 'user', text: "No, just generate a CSV report of all suspended accounts across all schools." },
  { id: 8, sender: 'ai', text: "Certainly. I have generated a CSV report containing 12 currently suspended accounts across 4 institutions.", type: 'document', documentTitle: 'suspended_accounts_report_2023.csv', documentType: 'CSV' },
  { id: 9, sender: 'user', text: "Perfect. Also, how many AI-generated quizzes were created platform-wide this month?" },
  { id: 10, sender: 'ai', text: "This month, teachers created 1,240 quizzes in total. Out of those, **793 (64%)** were completely generated by AI. This represents a 12% week-over-week increase in AI adoption!" },
  { id: 11, sender: 'user', text: "Schedule a global announcement for tomorrow morning at 8 AM regarding the new Quiz AI update." },
  { id: 12, sender: 'ai', text: "Drafting announcement:\n\n**Title:** New AI Features for Educators\n**Target:** All Teachers\n**Time:** Tomorrow, 08:00 AM EST\n\nI have queued this broadcast in the Announcements pipeline. Would you like me to confirm and schedule it?", hasAction: true },
];

const SuperAdminAICopilot = () => {
  const [messages, setMessages] = useState(mockChat);
  const [inputValue, setInputValue] = useState('');
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = () => {
    if (!inputValue.trim()) return;
    const newMessage = {
      id: messages.length + 1,
      sender: 'user',
      text: inputValue
    };
    setMessages([...messages, newMessage]);
    setInputValue('');
    
    // Mock AI response
    setTimeout(() => {
      setMessages(prev => [...prev, {
        id: prev.length + 1,
        sender: 'ai',
        text: "I am processing that administrative request. Since this is a demo, I cannot execute live database queries right now."
      }]);
    }, 1000);
  };

  return (
    <div className="h-[calc(100vh-5rem)] md:h-[calc(100vh-7rem)] flex gap-0 md:gap-6 relative">
      
      {/* Mobile Overlay Backdrop */}
      <AnimatePresence>
        {isSidebarOpen && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setIsSidebarOpen(false)}
            className="absolute inset-0 bg-gray-900/20 backdrop-blur-sm z-30 lg:hidden rounded-2xl"
          />
        )}
      </AnimatePresence>

      {/* History Sidebar */}
      <AnimatePresence initial={false}>
        {isSidebarOpen && (
          <motion.div 
            initial={{ width: 0, opacity: 0 }}
            animate={{ width: 224, opacity: 1 }}
            exit={{ width: 0, opacity: 0 }}
            transition={{ duration: 0.2, ease: "easeInOut" }}
            className="absolute left-0 lg:relative z-40 h-full flex flex-col bg-white rounded-2xl border border-gray-100 shadow-2xl lg:shadow-sm overflow-hidden shrink-0"
          >
            <div className="w-full flex flex-col h-full">
              <div className="p-4 border-b border-gray-100 flex items-center justify-between bg-gray-50/50 shrink-0">
                <h2 className="font-bold text-gray-900 flex items-center gap-2">
                  <FiMessageSquare className="text-indigo-600" /> History
                </h2>
                <div className="flex gap-2">
                  <button className="p-2 bg-white rounded-lg border border-gray-200 text-gray-500 hover:text-gray-900 hover:shadow-sm transition-all" title="New Chat">
                    <FiPlus />
                  </button>
                  <button onClick={() => setIsSidebarOpen(false)} className="lg:hidden p-2 bg-white rounded-lg border border-gray-200 text-gray-500 hover:text-gray-900 hover:shadow-sm transition-all" title="Close Sidebar">
                    <FiX />
                  </button>
                </div>
              </div>
              <div className="flex-1 overflow-y-auto p-3 space-y-1">
                {mockHistory.map((chat, i) => (
                  <button 
                    key={chat.id} 
                    className={`w-full text-left p-3 rounded-xl transition-colors text-sm ${i === 0 ? 'bg-[#2D2D2D] text-white shadow-md' : 'text-gray-600 hover:bg-gray-50'}`}
                  >
                    <p className="font-bold truncate">{chat.title}</p>
                    <p className={`text-[10px] uppercase tracking-wider mt-1 ${i === 0 ? 'text-gray-400' : 'text-gray-400'}`}>{chat.date}</p>
                  </button>
                ))}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main Chat Area */}
      <div className="flex-1 flex flex-col relative bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
        {/* Chat Feed */}
        <div className="flex-1 overflow-y-auto p-4 md:p-6 space-y-4 md:space-y-6 bg-slate-50/50">
          {messages.map((msg) => (
            <motion.div 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              key={msg.id} 
              className={`flex gap-4 max-w-3xl ${msg.sender === 'user' ? 'ml-auto flex-row-reverse' : ''}`}
            >
              <div className={`w-8 h-8 mt-1 rounded-full flex items-center justify-center shrink-0 shadow-sm ${msg.sender === 'user' ? 'bg-gray-900 text-white' : 'bg-indigo-500 text-white'}`}>
                {msg.sender === 'user' ? 'JS' : <FiCpu className="text-sm" />}
              </div>
              <div className={`flex flex-col gap-3 ${msg.sender === 'user' ? 'items-end' : 'items-start'}`}>
                <div className={`px-5 py-3.5 rounded-2xl text-sm font-medium leading-relaxed shadow-sm ${
                  msg.sender === 'user' 
                    ? 'bg-[#2D2D2D] text-white rounded-tr-sm' 
                    : 'bg-white border border-gray-100 text-gray-700 rounded-tl-sm'
                }`}>
                  {msg.text.split('\n').map((line, i) => (
                    <span key={i}>
                      {line.includes('**') ? (
                        <span dangerouslySetInnerHTML={{__html: line.replace(/\*\*(.*?)\*\*/g, '<strong class="font-black text-gray-900 bg-gray-100 px-1 py-0.5 rounded">$1</strong>')}} />
                      ) : line.includes('`') ? (
                        <span dangerouslySetInnerHTML={{__html: line.replace(/`(.*?)`/g, '<code class="bg-indigo-50 text-indigo-600 px-1 py-0.5 rounded">$1</code>')}} />
                      ) : line}
                      {i < msg.text.split('\n').length - 1 && <br />}
                    </span>
                  ))}
                </div>

                {msg.type === 'document' && (
                  <div className="bg-white border border-gray-200 rounded-xl p-3 md:p-4 flex items-center gap-3 md:gap-4 w-64 md:w-72 shadow-sm cursor-pointer hover:shadow-md transition-shadow group">
                    <div className="p-2.5 md:p-3 bg-green-50 text-green-600 rounded-lg group-hover:bg-indigo-50 group-hover:text-indigo-600 transition-colors">
                      <FiBarChart2 className="text-xl md:text-2xl" />
                    </div>
                    <div>
                      <p className="font-bold text-gray-900 text-xs md:text-sm truncate w-36 md:w-48 group-hover:text-indigo-600 transition-colors">{msg.documentTitle}</p>
                      <p className="text-[9px] md:text-xs text-gray-500 font-bold uppercase mt-0.5">{msg.documentType} Document</p>
                    </div>
                  </div>
                )}

                {msg.hasAction && (
                  <div className="flex gap-2 mt-1">
                    <button className="px-3 py-1.5 md:px-4 md:py-2 bg-indigo-600 text-white text-[10px] md:text-xs font-bold rounded-lg shadow-sm hover:bg-indigo-700 transition-colors">Confirm & Schedule</button>
                    <button className="px-3 py-1.5 md:px-4 md:py-2 bg-white border border-gray-200 text-gray-600 text-[10px] md:text-xs font-bold rounded-lg hover:bg-gray-50 transition-colors">Cancel</button>
                  </div>
                )}
              </div>
            </motion.div>
          ))}
          <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <div className="p-2 md:p-4 bg-white border-t border-gray-100 shrink-0 relative">
          
          <div className="relative max-w-4xl mx-auto flex items-center">
            <div className="absolute left-1 md:left-2 flex items-center gap-0 z-10">
              <button 
                onClick={() => setIsSidebarOpen(!isSidebarOpen)}
                className="text-indigo-500 hover:text-indigo-600 p-1.5 md:p-2 transition-colors rounded-full hover:bg-indigo-50" 
                title="Toggle History"
              >
                <FiSidebar className="text-[18px] md:text-[20px]" />
              </button>
              <button className="hidden sm:block text-gray-400 hover:text-gray-600 p-1.5 md:p-2 transition-colors rounded-full hover:bg-gray-100" title="Attach Document">
                <FiPaperclip className="text-[16px] md:text-[18px]" />
              </button>
              <button className="text-gray-400 hover:text-gray-600 p-1.5 md:p-2 transition-colors rounded-full hover:bg-gray-100" title="Upload Image">
                <FiImage className="text-[16px] md:text-[18px]" />
              </button>
            </div>
            
            <input 
              type="text" 
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  handleSend();
                }
              }}
              placeholder="Ask Copilot for stats or actions..."
              className="w-full bg-gray-50 border border-gray-200 rounded-full py-2.5 md:py-3.5 pl-[5.5rem] sm:pl-[7.5rem] pr-[4.5rem] md:pr-24 text-[13px] md:text-sm font-medium focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 focus:bg-white transition-all shadow-inner"
            />
            
            <div className="absolute right-1 md:right-2 flex items-center gap-0.5 md:gap-1.5">
              <button className="text-gray-400 hover:text-indigo-600 p-1.5 md:p-2 transition-colors rounded-full hover:bg-indigo-50" title="Voice Input">
                <FiMic className="text-[16px] md:text-[18px]" />
              </button>
              <button 
                onClick={handleSend}
                disabled={!inputValue.trim()}
                className="w-8 h-8 md:w-10 md:h-10 bg-indigo-600 hover:bg-indigo-700 text-white rounded-full flex items-center justify-center transition-all shadow-md disabled:opacity-50 disabled:cursor-not-allowed" 
                title="Send Message"
              >
                <FiSend className="mr-0.5 text-sm md:text-base" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SuperAdminAICopilot;
